development:
  adapter: postgresql
  database: potofgold_development
  encoding: utf8
  template: template0
  host: localhost

test:
    adapter: postgresql
    database: potofgold_test
    encoding: utf8
    template: template0
    host: localhost
